import type { AuditDomainData, AuditPeriod } from "./types";

function series(
	labels: string[],
	values: number[],
	secondary?: number[],
): Record<AuditPeriod, { label: string; value: number; secondary?: number }[]> {
	const points = labels.map((label, i) => ({
		label,
		value: values[i] ?? 0,
		secondary: secondary?.[i],
	}));
	return {
		"7d": points.slice(-7),
		"30d": points.slice(-10),
		"90d": points,
		ytd: points,
	};
}

export const USE_AUDIT_MOCK_DATA =
	process.env.NEXT_PUBLIC_AUDIT_MOCK_DATA !== "false";

export const auditDomainMockData: Record<
	AuditDomainData["domain"],
	AuditDomainData
> = {
	regulatory: {
		domain: "regulatory",
		label: "Regulatory & filings",
		description:
			"Federal and state filing deadlines, charitable registrations, and audit readiness.",
		caalmModule: "Reports & Analytics",
		modulePath: "/analytics",
		kpis: [
			{
				id: "filings",
				title: "Filings on time",
				value: "100%",
				description: "Last 3 reporting cycles",
				trend: "On track",
				trendDirection: "neutral",
				ragStatus: "green",
			},
			{
				id: "deadlines",
				title: "Upcoming deadlines",
				value: "4",
				description: "Next 90 days",
				trend: "+1",
				trendDirection: "up",
				ragStatus: "amber",
			},
			{
				id: "registrations",
				title: "State registrations",
				value: "3/3",
				description: "Active jurisdictions current",
				trend: "Current",
				trendDirection: "neutral",
				ragStatus: "green",
			},
			{
				id: "findings",
				title: "Open audit findings",
				value: "1",
				description: "Older than 12 months",
				trend: "-1",
				trendDirection: "down",
				ragStatus: "amber",
			},
		],
		timeSeries: series(
			["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
			[92, 93, 94, 95, 96, 97, 98, 99, 100, 100],
			[6, 5, 5, 4, 4, 3, 3, 2, 2, 1],
		),
		breakdown: [
			{ name: "Form 990", value: 1, fill: "#0f5384" },
			{ name: "State reg", value: 3, fill: "#03AFBF" },
			{ name: "Annual report", value: 2, fill: "#56B8FF" },
			{ name: "Grant reports", value: 5, fill: "#1E40AF" },
		],
		donut: [
			{ name: "On time", value: 88, fill: "#03AFBF" },
			{ name: "Due soon", value: 8, fill: "#F59E0B" },
			{ name: "Overdue", value: 4, fill: "#EF4444" },
		],
		evidence: [
			{
				id: "REG-001",
				title: "Form 990 annual return",
				owner: "Finance team",
				status: "compliant",
				dueDate: "2026-11-15",
				lastTested: "2026-06-01",
				category: "Federal filing",
				moduleLink: "/analytics",
				moduleLabel: "Reports",
			},
			{
				id: "REG-002",
				title: "CA charitable registration renewal",
				owner: "Compliance lead",
				status: "at_risk",
				dueDate: "2026-08-30",
				category: "State registration",
				moduleLink: "/settings/organization",
				moduleLabel: "Settings",
			},
			{
				id: "REG-003",
				title: "Single audit threshold review",
				owner: "Audit committee",
				status: "in_progress",
				dueDate: "2026-09-30",
				category: "Federal audit",
				moduleLink: "/audits/audit",
				moduleLabel: "Audit logs",
			},
		],
	},
	contracts: {
		domain: "contracts",
		label: "Contracts & grants",
		description:
			"Grant agreements, vendor contracts, and funder reporting obligations tracked in CAALM.",
		caalmModule: "Contracts",
		modulePath: "/contracts",
		kpis: [
			{
				id: "rate",
				title: "Compliance rate",
				value: "—",
				description: "Up-to-date contracts",
				trend: "Live data",
				trendDirection: "neutral",
			},
			{
				id: "action",
				title: "Action required",
				value: "—",
				description: "Needs follow-up",
				trendDirection: "neutral",
			},
			{
				id: "noncompliant",
				title: "Non-compliant",
				value: "—",
				description: "Critical gaps",
				trendDirection: "neutral",
			},
			{
				id: "expiring",
				title: "Expiring soon",
				value: "—",
				description: "Within 90 days",
				trendDirection: "neutral",
			},
		],
		timeSeries: series(
			["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
			[78, 80, 82, 84, 85, 87, 88, 89, 91, 92],
			[14, 13, 12, 11, 10, 9, 8, 7, 6, 5],
		),
		breakdown: [
			{ name: "Grants", value: 18, fill: "#0f5384" },
			{ name: "Vendor", value: 24, fill: "#03AFBF" },
			{ name: "Service", value: 12, fill: "#56B8FF" },
			{ name: "MOU", value: 8, fill: "#1E40AF" },
		],
		donut: [
			{ name: "Up-to-date", value: 72, fill: "#03AFBF" },
			{ name: "Action required", value: 18, fill: "#F59E0B" },
			{ name: "Non-compliant", value: 10, fill: "#EF4444" },
		],
		evidence: [
			{
				id: "CTR-101",
				title: "HUD community grant agreement",
				owner: "Program director",
				status: "compliant",
				dueDate: "2026-12-31",
				lastTested: "2026-07-01",
				category: "Federal grant",
				moduleLink: "/contracts",
				moduleLabel: "Contracts",
			},
			{
				id: "CTR-102",
				title: "County behavioral health MOU",
				owner: "Contracts admin",
				status: "at_risk",
				dueDate: "2026-08-15",
				category: "Interagency",
				moduleLink: "/contracts",
				moduleLabel: "Contracts",
			},
			{
				id: "CTR-103",
				title: "Facilities maintenance vendor",
				owner: "Operations",
				status: "non_compliant",
				dueDate: "2026-07-01",
				category: "Vendor",
				moduleLink: "/my-contracts",
				moduleLabel: "My contracts",
			},
		],
	},
	licenses: {
		domain: "licenses",
		label: "Licenses",
		description:
			"Organizational, professional, and program licenses with renewal tracking.",
		caalmModule: "Licenses",
		modulePath: "/licenses",
		kpis: [
			{
				id: "active",
				title: "Active licenses",
				value: "—",
				description: "Currently valid",
				trendDirection: "neutral",
			},
			{
				id: "expiring",
				title: "Expiring in 30 days",
				value: "—",
				description: "Renewal needed",
				trendDirection: "neutral",
			},
			{
				id: "atrisk",
				title: "At risk",
				value: "—",
				description: "Action required",
				trendDirection: "neutral",
			},
			{
				id: "renewal",
				title: "Renewal health",
				value: "—",
				description: "On-time renewals",
				trendDirection: "neutral",
			},
		],
		timeSeries: series(
			["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
			[94, 95, 95, 96, 96, 97, 97, 98, 98, 99],
			[8, 7, 7, 6, 6, 5, 5, 4, 4, 3],
		),
		breakdown: [
			{ name: "Program", value: 12, fill: "#0f5384" },
			{ name: "Professional", value: 28, fill: "#03AFBF" },
			{ name: "Facility", value: 6, fill: "#56B8FF" },
			{ name: "Insurance", value: 4, fill: "#1E40AF" },
		],
		donut: [
			{ name: "Compliant", value: 82, fill: "#03AFBF" },
			{ name: "At risk", value: 12, fill: "#F59E0B" },
			{ name: "Non-compliant", value: 6, fill: "#EF4444" },
		],
		evidence: [
			{
				id: "LIC-201",
				title: "Behavioral health program license",
				owner: "Clinical director",
				status: "compliant",
				dueDate: "2027-03-01",
				lastTested: "2026-06-15",
				category: "Program",
				moduleLink: "/licenses",
				moduleLabel: "Licenses",
			},
			{
				id: "LIC-202",
				title: "Residential facility certification",
				owner: "Compliance officer",
				status: "at_risk",
				dueDate: "2026-08-20",
				category: "Facility",
				moduleLink: "/licenses",
				moduleLabel: "Licenses",
			},
			{
				id: "LIC-203",
				title: "General liability insurance",
				owner: "Risk management",
				status: "pending",
				dueDate: "2026-09-01",
				category: "Insurance",
				moduleLink: "/licenses",
				moduleLabel: "Licenses",
			},
		],
	},
	documents: {
		domain: "documents",
		label: "Documents & evidence",
		description:
			"Policies, board records, grant documentation, and audit evidence stored in CAALM.",
		caalmModule: "Documents",
		modulePath: "/uploads",
		kpis: [
			{
				id: "complete",
				title: "Evidence completeness",
				value: "94%",
				description: "Required docs on file",
				trend: "+2%",
				trendDirection: "up",
				ragStatus: "green",
			},
			{
				id: "missing",
				title: "Missing evidence",
				value: "14",
				description: "Outstanding requests",
				trend: "-3",
				trendDirection: "down",
				ragStatus: "amber",
			},
			{
				id: "overdue",
				title: "Overdue uploads",
				value: "5",
				description: "Past due date",
				trend: "+1",
				trendDirection: "up",
				ragStatus: "amber",
			},
			{
				id: "grant",
				title: "Grant report docs",
				value: "18/20",
				description: "Current cycle submitted",
				trend: "+2",
				trendDirection: "up",
				ragStatus: "green",
			},
		],
		timeSeries: series(
			["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
			[180, 195, 210, 228, 245, 260, 275, 290, 302, 312],
			[22, 20, 18, 17, 16, 15, 14, 14, 13, 14],
		),
		breakdown: [
			{ name: "Policies", value: 54, fill: "#0f5384" },
			{ name: "Board mins", value: 42, fill: "#03AFBF" },
			{ name: "Grant reports", value: 38, fill: "#56B8FF" },
			{ name: "Vendor docs", value: 76, fill: "#1E40AF" },
		],
		donut: [
			{ name: "Complete", value: 94, fill: "#03AFBF" },
			{ name: "In review", value: 4, fill: "#56B8FF" },
			{ name: "Missing", value: 2, fill: "#EF4444" },
		],
		evidence: [
			{
				id: "DOC-101",
				title: "Q2 board meeting minutes",
				owner: "Board secretary",
				status: "compliant",
				dueDate: "2026-07-12",
				lastTested: "2026-07-11",
				category: "Governance",
				moduleLink: "/uploads",
				moduleLabel: "Documents",
			},
			{
				id: "DOC-102",
				title: "Conflict-of-interest disclosures",
				owner: "Governance committee",
				status: "at_risk",
				dueDate: "2026-07-31",
				category: "Board policy",
				moduleLink: "/uploads",
				moduleLabel: "Documents",
			},
			{
				id: "DOC-103",
				title: "Federal grant expenditure report",
				owner: "Grants manager",
				status: "non_compliant",
				dueDate: "2026-07-08",
				category: "Grant reporting",
				moduleLink: "/uploads",
				moduleLabel: "Documents",
			},
		],
	},
	governance: {
		domain: "governance",
		label: "Governance & teams",
		description:
			"Board accountability, team training, policy attestations, and role assignments.",
		caalmModule: "Team",
		modulePath: "/dashboard/user-management",
		kpis: [
			{
				id: "coi",
				title: "COI disclosures",
				value: "96%",
				description: "Board & leadership",
				trend: "+4%",
				trendDirection: "up",
				ragStatus: "green",
			},
			{
				id: "policies",
				title: "Policies reviewed",
				value: "38",
				description: "Current review cycle",
				trend: "+6",
				trendDirection: "up",
				ragStatus: "green",
			},
			{
				id: "training",
				title: "Training completion",
				value: "87%",
				description: "Staff certified",
				trend: "+5%",
				trendDirection: "up",
				ragStatus: "amber",
			},
			{
				id: "actions",
				title: "Open action items",
				value: "11",
				description: "From last board review",
				trend: "-4",
				trendDirection: "down",
				ragStatus: "amber",
			},
		],
		timeSeries: series(
			["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
			[72, 74, 76, 78, 80, 82, 84, 85, 86, 87],
			[14, 13, 12, 11, 12, 11, 10, 11, 11, 11],
		),
		breakdown: [
			{ name: "Administration", value: 12, fill: "#0f5384" },
			{ name: "Clinical", value: 18, fill: "#03AFBF" },
			{ name: "Residential", value: 9, fill: "#56B8FF" },
			{ name: "Child welfare", value: 7, fill: "#1E40AF" },
		],
		donut: [
			{ name: "Compliant", value: 78, fill: "#03AFBF" },
			{ name: "At risk", value: 14, fill: "#F59E0B" },
			{ name: "Non-compliant", value: 8, fill: "#EF4444" },
		],
		evidence: [
			{
				id: "GOV-301",
				title: "Code of conduct attestation",
				owner: "HR director",
				status: "compliant",
				dueDate: "2026-07-20",
				lastTested: "2026-07-09",
				category: "Staff policy",
				moduleLink: "/dashboard/user-management",
				moduleLabel: "Team",
			},
			{
				id: "GOV-302",
				title: "Whistleblower policy review",
				owner: "Board chair",
				status: "in_progress",
				dueDate: "2026-08-15",
				category: "Board governance",
				moduleLink: "/settings/organization",
				moduleLabel: "Settings",
			},
			{
				id: "GOV-303",
				title: "Mandatory reporter training",
				owner: "Training coordinator",
				status: "at_risk",
				dueDate: "2026-07-25",
				category: "Team training",
				moduleLink: "/team/tasks",
				moduleLabel: "Assign tasks",
			},
		],
	},
};

export function getAuditDomainData(
	domain: AuditDomainData["domain"],
): AuditDomainData {
	return auditDomainMockData[domain];
}

export function getTimeSeriesForPeriod(
	domain: AuditDomainData["domain"],
	period: AuditPeriod,
) {
	return auditDomainMockData[domain].timeSeries[period];
}
