export interface ContractEnterpriseMetadata {
	contractId?: string;
	orgId?: string;
	counterpartyContactName?: string;
	counterpartyContactTitle?: string;
	erpReference?: string;
	crmReference?: string;
	projectMatterId?: string;
	tags?: string[];
	businessPurpose?: string;
	primaryInternalContactId?: string;
	secondaryInternalContactId?: string;
	alertRecipientIds?: string[];
	alertEscalationContactIds?: string[];
	alertLeadTimes?: string[];
	alertChannels?: string[];
	alertNotes?: string;
	alertStrategy?: string;
	governingLaw?: string;
	jurisdiction?: string;
	disputeResolutionMethod?:
		| "litigation"
		| "arbitration"
		| "mediation"
		| "negotiation"
		| "hybrid"
		| "other";
	confidentialityClassification?:
		| "public"
		| "internal"
		| "confidential"
		| "restricted";
	recordsRetentionPeriodMonths?: number;
	insuranceCoveragePerIncident?: number;
	insuranceCoverageAggregate?: number;
	milestones?: string[];
	deliverables?: string[];
	slaPenalties?: string;
	escalationProcedures?: string;
	serviceCreditTerms?: string;
	obligationOwners?: string[];
	approvalDueDate?: string;
	approvalEscalationContactIds?: string[];
	workflowNotes?: string;
	digitalSignaturePlatform?: string;
	digitalSignatureStatus?:
		| "not_started"
		| "pending"
		| "completed"
		| "declined"
		| "expired";
	digitalSignatureCompletedAt?: string;
	digitalSignatureEnvelopeId?: string;
	signatureRecipientIds?: string[];
	riskMitigationPlan?: string;
	visibilityRoles?: string[];
	searchKeywords?: string;
	accessScope?: string;
	digitalSignatureRequired?: boolean;
}

export interface ContractMetadataPayload {
	contractName?: string;
	contractType?: string;
	contractCategory?: string;
	contractNumber?: string;
	description?: string;
	orgId?: string;
	assignToDepartment?: string;
	department?: string;
	departmentOwner?: string;
	businessUnit?: string;
	subDepartment?: string;
	contractOwnerId?: string;
	contractExpiryDate?: string;
	startDate?: string;
	executionDate?: string;
	autoRenew?: boolean;
	renewalNoticeDays?: number;
	amount?: number;
	currencyCode?: string;
	notToExceedAmount?: number;
	paymentTerms?: string;
	paymentSchedule?: string;
	budgetCode?: string;
	costCenter?: string;
	riskLevel?: "critical" | "high" | "medium" | "low";
	lifecycleStatus?: string;
	counterpartyLegalName?: string;
	counterpartyContactTitle?: string;
	counterpartyContactEmail?: string;
	counterpartyContactPhone?: string;
	counterpartyAddress?: string;
	counterpartyType?: string;
	counterpartyTaxId?: string;
	counterpartyDunsNumber?: string;
	insuranceRequired?: boolean;
	insuranceVerifiedDate?: string;
	insuranceExpiryDate?: string;
	insuranceCoveragePerIncident?: number;
	insuranceCoverageAggregate?: number;
	indemnificationIncluded?: boolean;
	hipaaRequired?: boolean;
	dataPrivacyRequirements?: string;
	backgroundCheckRequired?: boolean;
	regulatoryRequirements?: string;
	auditRightsGranted?: boolean;
	keyObligations?: string[];
	serviceLevelAgreements?: string;
	performanceMetrics?: string;
	reportingRequirements?: string;
	postTerminationObligations?: string;
	terminationNoticeDays?: number;
	terminationRights?: string;
	curePeriodDays?: number;
	attachmentReferences?: string[];
	relatedDocumentIds?: string[];
	versionNumber?: string;
	parentContractId?: string;
	templateUsed?: string;
	approvalWorkflowTemplate?: string;
	approvalWorkflowState?: string;
	internalApproverIds?: string[];
	currentApprovalStage?: string;
	approvalHistoryLog?: string;
	reviewerComments?: string;
	assignedManagers?: string[];
	compliance?: string;
	priority?: string;
	vendor?: string;
	selectedContractType?: string;
	grantTerms?: string;
	donorRestrictions?: string;
	projectDescription?: string;
	propertyDescription?: string;
	enterpriseMetadata?: ContractEnterpriseMetadata;
	deletedAt?: string | null;
	deletedBy?: string | null;
}
