import type { AuditEvidenceMapRow } from "./types";

/** CFCE-like FQHC + child welfare + nonprofit financial PBC (non-finance slice) */
export const CFCE_EVIDENCE_MAP_SEED: Omit<AuditEvidenceMapRow, "$id">[] = [
	{
		segment: "cfce_fqhc_cw",
		auditType: "hrsa_osv",
		requirementId: "HRSA-SVC-CONTRACT",
		label: "Written contracts/agreements for required & additional services",
		evidenceType: "contract_agreement",
		caalmModule: "contracts",
		inV1: true,
		notes: "HRSA sampling of Column I/III service arrangements",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "hrsa_osv",
		requirementId: "HRSA-CRED-PRIV",
		label: "Credentialing and privileging documentation sample",
		evidenceType: "license_credential",
		caalmModule: "licenses",
		inV1: true,
		notes: "Clinical licenses / privileging files",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "hrsa_osv",
		requirementId: "HRSA-BOARD-GOV",
		label: "Board composition / governance documentation",
		evidenceType: "governance_doc",
		caalmModule: "governance",
		inV1: false,
		notes: "Out of live score in V1; map only",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "cw_monitoring",
		requirementId: "CW-PROVIDER-CONTRACT",
		label: "Active provider / lead-agency service contract",
		evidenceType: "contract_agreement",
		caalmModule: "contracts",
		inV1: true,
		notes: "CBC/provider monitoring contract file + term dates",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "cw_monitoring",
		requirementId: "CW-HOME-LICENSE",
		label: "Foster / group home or facility licensing",
		evidenceType: "license_credential",
		caalmModule: "licenses",
		inV1: true,
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "cw_monitoring",
		requirementId: "CW-STAFF-CRED",
		label: "Staff credentials required by contract",
		evidenceType: "license_credential",
		caalmModule: "licenses",
		inV1: true,
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "cw_monitoring",
		requirementId: "CW-CAP",
		label: "Corrective action plan items with owners and due dates",
		evidenceType: "corrective_action",
		caalmModule: "contracts",
		inV1: true,
		notes: "Mapped via non-compliant / action-required contracts",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "financial_pbc",
		requirementId: "PBC-GRANT-AGREEMENTS",
		label: "Grant and contract award agreements",
		evidenceType: "contract_agreement",
		caalmModule: "contracts",
		inV1: true,
		notes: "Financial PBC non-GL slice",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "financial_pbc",
		requirementId: "PBC-VENDOR-CONTRACTS",
		label: "Material vendor / service contracts",
		evidenceType: "contract_agreement",
		caalmModule: "contracts",
		inV1: true,
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "financial_pbc",
		requirementId: "PBC-INSURANCE",
		label: "Insurance certificates / coverage evidence",
		evidenceType: "license_or_document",
		caalmModule: "licenses",
		inV1: true,
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "financial_pbc",
		requirementId: "PBC-POLICIES",
		label: "Fiscal and compliance policy manuals",
		evidenceType: "policy_doc",
		caalmModule: "documents",
		inV1: false,
		notes: "Documents domain not live-scored in V1",
	},
	{
		segment: "cfce_fqhc_cw",
		auditType: "hrsa_osv",
		requirementId: "SITE-PUBLIC-PRESENCE",
		label: "Public website reachability (informational)",
		evidenceType: "site_crawl",
		caalmModule: "site",
		inV1: true,
		notes: "Optional crawl; not included in readiness score",
	},
];
