#!/usr/bin/env node

/**
 * Development setup script
 * Automatically configures environment for development
 */

const fs = require("node:fs");
const path = require("node:path");

const devEnvContent = `# Development Environment Configuration
# Auto-generated by setup-dev.js

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_REDIRECT_URI=http://localhost:3000/api/auth/callback/microsoft

# Microsoft OAuth Configuration
MICROSOFT_CLIENT_ID=8c92266f-85e1-4a5b-89d1-204225749459
MICROSOFT_CLIENT_SECRET=your_actual_secret_value
MICROSOFT_TENANT_ID=e2975cee-a30e-41db-982e-80ba44a89c59

# Appwrite Configuration
NEXT_PUBLIC_APPWRITE_CALENDAR_INTEGRATIONS_COLLECTION=6912da7c00567cdef123
`;

const _prodEnvContent = `# Production Environment Configuration
# Auto-generated by setup-dev.js

NEXT_PUBLIC_APP_URL=https://www.caalmsolutions.com
NEXT_PUBLIC_REDIRECT_URI=https://www.caalmsolutions.com/api/auth/callback/microsoft

# Microsoft OAuth Configuration
MICROSOFT_CLIENT_ID=8c92266f-85e1-4a5b-89d1-204225749459
MICROSOFT_CLIENT_SECRET=your_production_secret_value
MICROSOFT_TENANT_ID=e2975cee-a30e-41db-982e-80ba44a89c59

# Appwrite Configuration
NEXT_PUBLIC_APPWRITE_CALENDAR_INTEGRATIONS_COLLECTION=6912da7c00567cdef123
`;

function setupEnvironment() {
	const envPath = path.join(process.cwd(), ".env.local");

	console.log("🚀 Setting up development environment...");

	// Check if .env.local already exists
	if (fs.existsSync(envPath)) {
		console.log(
			"⚠️  .env.local already exists. Backing up to .env.local.backup",
		);
		fs.copyFileSync(envPath, `${envPath}.backup`);
	}

	// Write development environment
	fs.writeFileSync(envPath, devEnvContent);

	console.log("✅ Development environment configured!");
	console.log(
		"📝 Please update MICROSOFT_CLIENT_SECRET in .env.local with your actual secret",
	);
	console.log('🔧 Run "pnpm run dev" to start development server');
}

if (require.main === module) {
	setupEnvironment();
}

module.exports = { setupEnvironment };
